{% set name = "bmi-topography" %}
{% set version = "0.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/csdms/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 738df2b95b3a6924542383313d9ef739f2fbc649ec6f4103a74d651510c493d3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - bmi-topography=bmi_topography.cli:main

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy
    - rioxarray
    - requests
    - pyyaml
    - click
    - bmipy

test:
  imports:
    - bmi_topography
  commands:
    - bmi-topography --version
    - bmi-topography --help

about:
  home: https://csdms.colorado.edu/wiki/DataComponents
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: |
    Fetch and cache land elevation data from OpenTopography
  description: |
    bmi-topography is a Python library that allows a user to fetch and cache
    land elevation data from multiple sources using the OpenTopography REST API.
    It presents the user with an API, CLI, and BMI.
  doc_url: https://bmi-topography.readthedocs.io
  dev_url: https://github.com/csdms/bmi-topography

extra:
  recipe-maintainers:
    - mdpiper
