{% set name = "bmi-topography" %}
{% set version = "0.9.0" %}
# {% set python_min = python_min|default("3.10") %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/csdms/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8d9a010ea73fd734b23f4ea99e15e2aff794fbe713fee47281cc8bb847b670ee

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - bmi-topography=bmi_topography.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - rioxarray
    - requests
    - pyyaml
    - click
    - bmipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - bmi_topography
  commands:
    - bmi-topography --version
    - bmi-topography --help

about:
  home: https://csdms.colorado.edu/wiki/DataComponents
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: |
    Fetch and cache land elevation data from OpenTopography
  description: |
    bmi-topography is a Python library that allows a user to fetch and cache
    land elevation data from multiple sources using the OpenTopography REST API.
    It presents the user with an API, CLI, and BMI.
  doc_url: https://bmi-topography.readthedocs.io
  dev_url: https://github.com/csdms/bmi-topography

extra:
  recipe-maintainers:
    - mdpiper
