{% set name = "bmi-topography" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/csdms/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 432b6a8172fcf275ce7ddaab91b36c6e6062164f062736e257c67a9cbe5d0a34

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - bmi-topography=bmi_topography.cli:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - rioxarray
    - requests
    - pyyaml
    - click
    - bmipy

test:
  imports:
    - bmi_topography
  commands:
    - bmi-topography --version
    - bmi-topography --help

about:
  home: https://github.com/csdms/bmi-topography
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: |
    Fetch and cache land elevation data from OpenTopography
  description: |
    bmi-topography is a Python library that allows a user to fetch and cache
    land elevation data from multiple sources using the OpenTopography REST API.
    It presents the user with an API, CLI, and BMI.
  doc_url: https://bmi-topography.readthedocs.io
  dev_url: https://github.com/csdms/bmi-topography

extra:
  recipe-maintainers:
    - mdpiper
