{% set name = "bmi-topography" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/csdms/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5b2f8f2b921b18186b44c37aaec7593772009bf1909843d033f87ee7bafd823b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - bmi-topography=bmi_topography.cli:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - rasterio
    - xarray
    - requests
    - pyyaml
    - click
    - bmipy

test:
  imports:
    - bmi_topography
  commands:
    - bmi-topography --version
    - bmi-topography --help

about:
  home: https://github.com/csdms/bmi-topography
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: |
    Fetch and cache NASA Shuttle Radar Topography Mission (SRTM) land elevation data
  description: |
    bmi-topography is a Python library that allows a user to fetch and cache
    NASA Shuttle Radar Topography Mission (SRTM) land elevation data using the
    OpenTopography REST API. It presents the user with an API, CLI, and BMI.
  doc_url: https://bmi-topography.readthedocs.io
  dev_url: https://github.com/csdms/bmi-topography

extra:
  recipe-maintainers:
    - mdpiper
